export const UserPermissions = {
  CREATE_USER: 'create:user',
  MODIFY_USER: 'modify:user',
  VIEW_USER: 'view:user',
  CREATE_SUPPLIER: 'create:supplier',
  MODIFY_SUPPLIER: 'modify:supplier',
  VIEW_SUPPLIER: 'view:supplier',
  CREATE_PAYMENT_METHOD: 'create:payment-method',
  MODIFY_PAYMENT_METHOD: 'modify:payment-method',
  VIEW_PAYMENT_METHOD: 'view:payment-method',
  CREATE_PRODUCT: 'create:product',
  MODIFY_PRODUCT: 'modify:product',
  VIEW_PRODUCT: 'view:product',
  CREATE_SALE: 'create:sale',
  VIEW_SALE: 'view:sale',
  CREATE_CUSTOMER: 'create:customer',
  MODIFY_CUSTOMER: 'modify:customer',
  VIEW_CUSTOMER: 'view:customer',
} as const;
